name: Validation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          python -m pip install -q -r requirements.txt
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: jupyter-actions
          enviroment-file: environment.yml
          python-version: 3.9
         
      - name: check notebook state and make sure outputs and execution_count is removed
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Validate runnability
        run: |
          jupyter nbconvert --execute *.ipynb

      - name: Valudate unit test
        shell: bash -l {0}
        run: |
          conda activate jupyter-actions
          pytest
